inherit_from:
  - .rubocop_airbnb.yml

Rails:
  Enabled: true

AllCops:
  Exclude:
    - "db/**/*"
    - "bin/*"
    - "vendor/*"
    - "config/environments/*"
    - "config/initializers/*"
    - "config/routes.rb"
    - "spec/spec_helper.rb"
    - "node_modules/**/*"
