version: '3'
services:
  db:
    image: postgres:13
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: <%= Rails.application.credentials.db[:postgres_password] %>
  chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - 4444:4444
  manu_match:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/manu_match
    environment:
      BUNDLE_APP_CONFIG: /manu_match/.bundle
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: <%= Rails.application.credentials.db[:postgres_password] %>
    ports:
      - "3000:3000"
    depends_on:
      - db
      - chrome
    tmpfs:
      - /tmp
    stdin_open: true
    tty: true
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b 0.0.0.0"