version: '3'
services:
  db:
    image: postgres
    environment:
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: <%= Rails.application.credentials.db[:postgres_password] %>
  chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - 4444:4444
  manu_match:
    build:
      context: .
      dockerfile: Dockerfile.ci
    container_name: manu_match_app
    ports:
      - "3000:3000"
    environment:
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: <%= Rails.application.credentials.db[:postgres_password] %>
    depends_on:
      - db
      - chrome
    command: bundle exec rails server -b 0.0.0.0