version: 2.1
jobs:
  rspec:
    working_directory: ~/manu_match
    docker:
      - image: circleci/ruby:2.7.1-node
        environment:
          PGHOST: 127.0.0.1
          RAILS_ENV: test
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - gemfiles-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
      - run:
          name: Setup environment variable
          command: echo "export COMPOSE_FILE=docker-compose.ci.yml" >> $BASH_ENV
      - run: bundle config --local path vendor/bundle
      - run:
          name: bundle install
          command: bundle check || bundle install --jobs=8 --clean
      - run:
          name: install dependencies
          command: yarn install
      - save_cache:
          key: gemfiles-{{ .Branch }}-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}
          paths:
            - ./vendor/bundle
            - ./node_modules
      - run:
          name: Start containers
          command: |
            set -x
            docker-compose up --build -d
      - run:
          name: db:migrate
          command: |
            set -x
            docker exec manu_match_app bundle exec rails db:create
            docker exec manu_match_app bundle exec rails db:migrate
            docker exec manu_match_app bundle exec rails db:seed
      # - run:
      #     name: webpacker
      #     command: docker exec manu_match_app bundle exec bin/webpack
      - run:
          name: Run rspec
          command: docker exec manu_match_app bundle exec rspec
      - run:
          name: Stop containers
          command: docker-compose stop

  rubocop:
    working_directory: ~/manu_match
    docker:
      - image: circleci/ruby:2.7.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - gemfiles-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
      - run: bundle config --local path vendor/bundle
      - run:
          name: bundle install
          command: bundle check || bundle install --jobs=8 --clean
      - run:
          name: Run rubocop
          command: bundle exec rubocop --parallel

  brakeman:
    working_directory: ~/manu_match
    docker:
      - image: circleci/ruby:2.7.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - gemfiles-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
      - run: bundle config --local path vendor/bundle
      - run:
          name: bundle install
          command: bundle check || bundle install --jobs=8 --clean
      - run:
          name: Run brakeman
          command: bundle exec brakeman

  heroku_deploy:
    working_directory: ~/manu_match
    docker:
      - image: sue445/heroku-cli
    steps:
      - checkout
      - build-tools/install-ci-tools
      - jq/install
      - run:
          name: Identify who I am
          command: echo 'export MY_EMAIL=`heroku auth:whoami | tail -n 1`' >> $BASH_ENV
      - run:
          name: Deploy
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
      - run:
          name: Run post-deploy tasks
          command: |
            heroku config:set AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            heroku config:set AWS_HOST_NAME=$AWS_HOST_NAME
            heroku config:set AWS_REGION=$AWS_REGION
            heroku config:set AWS_BUCKET_NAME=$AWS_BUCKET_NAME
            heroku config:set RAILS_MASTER_KEY=$RAILS_MASTER_KEY
            heroku run_app bundle exec rails db:migrate
            heroku run_app bundle exec rails db:seed

orbs:
  build-tools: circleci/build-tools@2.7.0
  jq: circleci/jq@2.2.0
workflows:
  version: 2.1
  build:
    jobs:
      - rspec
      # - rubocop
      # - brakeman
      # - heroku_deploy:
      #     requires:
      #       - rspec
      #       - rubocop
      #       - brakeman
