version: 2.1
jobs:
  rspec:
    working_directory: ~/manu_match
    docker:
      - image: circleci/ruby:2.7.1
    environment:
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install docker-compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
      - run: bundle config --local path vendor/bundle
      - run:
          name: bundle install
          command: bundle check || bundle install --jobs=8 --clean
      - run:
          name: Setup environment variable
          command: |
            echo "export COMPOSE_FILE=docker-compose.ci.yml" >> $BASH_ENV
      - run:
          name: Start containers
          command: |
            set -x
            docker-compose up -d
      - run:
          name: Run rspec
          command: bundle exec rspec

  rubocop:
    working_directory: ~/manu_match
    docker:
      - image: circleci/ruby:2.7.1
    steps:
      - checkout
      - run: bundle config --local path vendor/bundle
      - run:
          name: bundle install
          command: bundle check || bundle install --jobs=8 --clean
      - run:
          name: Run rubocop
          command: bundle exec rubocop --parallel

  brakeman:
    working_directory: ~/manu_match
    docker:
      - image: circleci/ruby:2.7.1
    steps:
      - checkout
      - run: bundle config --local path vendor/bundle
      - run:
          name: bundle install
          command: bundle check || bundle install --jobs=8 --clean
      - run:
          name: Run brakeman
          command: bundle exec brakeman

  heroku_deploy:
    working_directory: ~/manu_match
    docker:
      - image: sue445/heroku-cli
    steps:
      - checkout
      - build-tools/install-ci-tools
      - jq/install
      - run:
          name: Identify who I am
          command: echo 'export MY_EMAIL=`heroku auth:whoami | tail -n 1`' >> $BASH_ENV
      - run:
          name: Deploy
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
      - run:
          name: Run post-deploy tasks
          command: |
            heroku config:set AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            heroku config:set AWS_HOST_NAME=$AWS_HOST_NAME
            heroku config:set AWS_REGION=$AWS_REGION
            heroku config:set AWS_BUCKET_NAME=$AWS_BUCKET_NAME
            heroku config:set RAILS_MASTER_KEY=$RAILS_MASTER_KEY
            heroku run bin/rails db:migrate
            heroku run bin/rails db:seed

orbs:
  build-tools: circleci/build-tools@2.7.0
  jq: circleci/jq@2.2.0
workflows:
  version: 2.1
  build:
    jobs:
      - rspec
      - rubocop
      - brakeman
      - heroku_deploy:
          requires:
            - rspec
            - rubocop
            - brakeman
