version: 2.1
jobs:
  rspec:
    working_directory: ~/manu_match
    docker:
      - image: cimg/ruby:2.7.1-node
        environment:
          PGHOST: 127.0.0.1
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - restore_cache:
          keys:
            - gemfiles-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
      - run:
          name: Setup environment variable
          command: echo "export COMPOSE_FILE=docker-compose.ci.yml" >> $BASH_ENV
      - save_cache:
          key: gemfiles-{{ .Branch }}-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}
          paths:
            - ./vendor/bundle
            - ./node_modules
      - run:
          name: Start containers
          command: |
            set -x
            docker-compose up --build -d
      - run:
          name: db:migrate
          command: |
            set -x
            docker exec manu_match_app bundle exec rails db:create
            docker exec manu_match_app bundle exec rails db:migrate
            docker exec manu_match_app bundle exec rails db:seed
      - run:
          name: Run rspec
          command: docker exec manu_match_app bundle exec rspec
      - run:
          name: Stop containers
          command: docker-compose stop

  rubocop:
    working_directory: ~/manu_match
    docker:
      - image: circleci/ruby:2.7.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - gemfiles-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
      - run: bundle config --local path vendor/bundle
      - run:
          name: bundle install
          command: bundle check || bundle install --jobs=8 --clean
      - run:
          name: Run rubocop
          command: bundle exec rubocop --parallel

  brakeman:
    working_directory: ~/manu_match
    docker:
      - image: circleci/ruby:2.7.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - gemfiles-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
      - run: bundle config --local path vendor/bundle
      - run:
          name: bundle install
          command: bundle check || bundle install --jobs=8 --clean
      - run:
          name: Run brakeman
          command: bundle exec brakeman

  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git
orbs:
  heroku: circleci/heroku@1.2.3
workflows:
  version: 2.1
  build:
    jobs:
      # - rspec
      # - rubocop
      # - brakeman
      - heroku/deploy-via-git:
          post-steps:
            - run: heroku run_app bundle exec rails db:migrate
          # requires:
          #   - rspec
          #   - rubocop
          #   - brakeman